#! /bin/sh

me="$(cat list)"
docker run \
	--env "PYRAR_CATALOG_SUFFIX=pyrar.localhost" \
	--env "PYRAR_MASTERS=10.10.10.10" \
	--env "PYRAR_NOTIFY_LIST=10.10.10.10" \
	-p 192.168.1.145:53:53 -p 192.168.1.145:53:53/udp \
	-p 127.0.0.1:53:53 -p 127.0.0.1:53:53/udp \
	-it ${me} $*
