#! /bin/sh

for me in $(cat list)
do
	id=$(docker image ls | awk '{ if($1=="'"${me}"'") print $3 }')
	ver="$(date +%Y-%m-%d)"
	if test "$1"; then ver="$1"; fi

	docker tag ${id} jamesstevens/${me}
	docker push jamesstevens/${me}

	docker tag ${id} jamesstevens/${me}:${ver}
	docker push jamesstevens/${me}:${ver}
done
