#! /bin/sh
##########################################################################
#    (c) Copyright 2021-2023 JRCS Ltd - All Rights Reserved              #
##########################################################################

base="/opt/named"
conf="${base}/etc/bind/named.conf"
envsub ${conf}.pre > ${conf}
chown named: ${conf}

extra="-4"
if test "${WITH_BIND_V6}" = "Y"; then extra=""; fi

if ! named-checkconf -t ${base}
	then
		echo "======= ERROR ========"
		sleep 5
		exit 1
	fi

exec /usr/sbin/named -f ${extra} -u named -t ${base}
