#! /bin/sh
##########################################################################
#    (c) Copyright 2021-2023 JRCS Ltd - All Rights Reserved              #
##########################################################################

base="/opt/named"
conf="${base}/etc/bind/named.conf"

if ! test "${PYRAR_CATALOG_SUFFIX}"
	then
		export PYRAR_CATALOG_SUFFIX="pyrar.localhost"
	fi

envsub ${conf}.pre > ${conf}
chown named: ${conf} ${base}/zones
chmod 755 ${base}/zones

extra="-4"
if test "${WITH_BIND_V6}" = "Y"; then extra=""; fi

if ! named-checkconf -t ${base}
	then
		echo "======= ERROR ========"
		sleep 5
		exit 1
	fi

exec /usr/sbin/named -f ${extra} -u named -t ${base}
