#! /bin/sh

docker run \
	--env PDNS_API_KEY=Some-Api-Key \
	-v /opt/github/pyrar/etc:/opt/pyrar/etc \
	-v /opt/github/pyrar/htdocs:/opt/pyrar/htdocs \
	-v /opt/github/pyrar/python:/opt/pyrar/python \
	-v /opt/github/pyrar/storage:/opt/pyrar/storage \
	-v /opt/github/pyrar/emails:/opt/pyrar/emails \
	-v /opt/github/pyrar/pems:/opt/pyrar/pems \
	--env BASE="/opt/pyrar" \
	--env PYTHONPATH="/opt/pyrar/python" \
	-p 10000:10000 \
	-p 10001:10001 \
	-p 8081:8081 \
	-p 127.0.0.1:80:80 \
	-p 192.168.1.145:80:80 \
	-p 192.168.1.145:443:443 \
	-p 192.168.1.145:1000:1000 \
	-p 127.0.0.1:443:443 \
	-p 192.168.1.145:53:53/udp -p 192.168.1.145:53:53 \
	-p 127.0.0.1:53:53/udp -p 127.0.0.1:53:53 \
	-it pyrar $*
