
kern.*         -/opt/pyrar/storage/logs/kern.log

*.info;*.!warn;kern.none;cron.none;mail.none;authpriv.none;\
        authpriv.none;local1.none;local2.none;local3.none;\
        local4.none;local5.none;local6.none;local7.none;\
        local0.none;uucp.none;cron.none;mail.none;\
        news.none -/opt/pyrar/storage/logs/messages

*.warn;kern.none;cron.none;mail.none;authpriv.none;\
        authpriv.none;local1.none;local2.none;local3.none;\
        local4.none;local5.none;local6.none;local7.none;\
        local0.none;uucp.none;cron.none;mail.none;\
        news.none -/opt/pyrar/storage/logs/syslog


authpriv.*      -/opt/pyrar/storage/logs/auth.log
cron.*          -/opt/pyrar/storage/logs/cron.log

local0.*        -/opt/pyrar/storage/logs/local0.log
local1.*        -/opt/pyrar/storage/logs/local1.log
local2.*        -/opt/pyrar/storage/logs/local2.log
local3.*        -/opt/pyrar/storage/logs/local3.log
local4.*        -/opt/pyrar/storage/logs/local4.log
local5.*        -/opt/pyrar/storage/logs/local5.log
local6.*        -/opt/pyrar/storage/logs/local6.log
local7.*        -/opt/pyrar/storage/logs/local7.log
uucp.*          -/opt/pyrar/storage/logs/uucp.log
mail.*          -/opt/pyrar/storage/logs/mail.log
