#! /bin/bash

limit=50; burst=10
low=30; lowb=5

for cmd in iptables ip6tables
do
	${cmd} -F
	${cmd} -N UDPDNS 2>/dev/null
	${cmd} -N DNSAUTH 2>/dev/null

	${cmd} -A INPUT -i lo -j ACCEPT
	${cmd} -A INPUT -i eth0 -j ACCEPT
done

iptables -A INPUT -p icmp -j ACCEPT
ip6tables -A INPUT -p ipv6-icmp -j ACCEPT

for cmd in iptables ip6tables
do

	${cmd} -A INPUT -p udp --sport 123 -m state --state ESTABLISHED,RELATED -j ACCEPT

	${cmd} -A INPUT -p udp --sport 53 -m state --state ESTABLISHED,RELATED -j ACCEPT
	${cmd} -A INPUT -p tcp --sport 53 -m state --state ESTABLISHED,RELATED -j ACCEPT


	${cmd} -A INPUT -p udp --dport 5300 -j DNSAUTH
	${cmd} -A INPUT -p udp --dport 53 -j UDPDNS

	${cmd} -A INPUT -i eth1 -p tcp --dport 5300 --syn -j LOG --log-prefix "HND-XFR"

	${cmd} -A DNSAUTH -m u32 --u32 '0x1b&0xff0001=1' -j DROP
	${cmd} -A DNSAUTH -m u32 --u32 '0x1b&0x1=1' -j DROP
	${cmd} -A DNSAUTH -m limit --limit ${limit} --limit-burst ${burst} -j ACCEPT
	${cmd} -A DNSAUTH -j DROP


	# TYPE=ANY for queries with no cookie
	${cmd} -A UDPDNS -m u32 --u32 '0x16&0xff@3&0xff=0xff' -j DROP

	# ${cmd} -A UDPDNS -m u32 --u32 '0x1b&0xff0001=1' -j DROP
	# ${cmd} -A UDPDNS -m u32 --u32 '0x1b&0x1=1' -m limit --limit 5 --limit-burst 2 -j ACCEPT
	# ${cmd} -A UDPDNS -m u32 --u32 '0x1b&0x1=1' -j DROP

	${cmd} -A UDPDNS --match length --length 0:50 -j DROP
	${cmd} -A UDPDNS -m limit --limit ${limit} --limit-burst ${burst} -j ACCEPT

	x=50
	g=5
	while test ${x} -lt 150
	do
			${cmd} -A UDPDNS --match length --length ${x}:$[${x}+${g}-1] -m limit --limit ${low} --limit-burst ${lowb} -j ACCEPT
			x=$[${x}+${g}]
	done
	${cmd} -A UDPDNS --match length --length 150:250 -m limit --limit ${low} --limit-burst ${lowb} -j ACCEPT

	${cmd} -A UDPDNS -j DROP

	${cmd} -A INPUT -p tcp --dport 53 -m state --state ESTABLISHED,RELATED -j ACCEPT
	${cmd} -A INPUT -p tcp --dport 53 -m limit --limit ${limit} --limit-burst ${burst} -j ACCEPT
	${cmd} -A INPUT -p tcp --dport 53 -j DROP
	${cmd} -A INPUT -p tcp --dport 5300 -m limit --limit ${limit} --limit-burst ${burst} -j ACCEPT
	${cmd} -A INPUT -p tcp --dport 5300 -j DROP

	${cmd} -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

	${cmd} -A INPUT -j DROP
done
