const supported_cryptos = [
	 [ "BTC", "Bitcoin" ],
	 [ "ETH", "Ethereum" ],
	 [ "USDT", "Tether USDt" ],
	 [ "XRP", "XRP" ],
	 [ "BNB", "BNB" ],
	 [ "SOL", "Solana" ],
	 [ "USDC", "USDC" ],
	 [ "DOGE", "Dogecoin" ],
	 [ "TRX", "TRON" ],
	 [ "ADA", "Cardano" ],
	 [ "HYPE", "Hyperliquid" ],
	 [ "USDe", "Ethena USDe" ],
	 [ "LINK", "Chainlink" ],
	 [ "AVAX", "Avalanche" ],
	 [ "XLM", "Stellar" ],
	 [ "SUI", "Sui" ],
	 [ "BCH", "Bitcoin Cash" ],
	 [ "HBAR", "Hedera" ],
	 [ "LEO", "UNUS SED LEO" ],
	 [ "LTC", "Litecoin" ],
	 [ "TON", "Toncoin" ],
	 [ "SHIB", "Shiba Inu" ],
	 [ "CRO", "Cronos" ],
	 [ "DOT", "Polkadot" ],
	 [ "MNT", "Mantle" ],
	 [ "DAI", "Dai" ],
	 [ "XMR", "Monero" ],
	 [ "WLFI", "World Liberty Financial" ],
	 [ "UNI", "Uniswap" ],
	 [ "AAVE", "Aave" ],
	 [ "ENA", "Ethena" ],
	 [ "OKB", "OKB" ],
	 [ "PEPE", "Pepe" ],
	 [ "BGB", "Bitget Token" ],
	 [ "NEAR", "NEAR Protocol" ],
	 [ "ASTER", "Aster" ],
	 [ "TAO", "Bittensor" ],
	 [ "APT", "Aptos" ],
	 [ "ETC", "Ethereum Classic" ],
	 [ "ONDO", "Ondo" ],
	 [ "IP", "Story" ],
	 [ "USD1", "World Liberty Financial USD" ],
	 [ "WLD", "Worldcoin" ],
	 [ "M", "MemeCore" ],
	 [ "POL", "Polygon (prev. MATIC)" ],
	 [ "ARB", "Arbitrum" ],
	 [ "ICP", "Internet Computer" ],
	 [ "PI", "Pi" ],
	 [ "XPL", "Plasma" ],
	 [ "KAS", "Kaspa" ],
	 [ "PYUSD", "PayPal USD" ],
	 [ "KCS", "KuCoin Token" ],
	 [ "ATOM", "Cosmos" ],
	 [ "VET", "VeChain" ],
	 [ "MYX", "MYX Finance" ],
	 [ "PUMP", "Pump.fun" ],
	 [ "ALGO", "Algorand" ],
	 [ "FLR", "Flare" ],
	 [ "RENDER", "Render" ],
	 [ "PENGU", "Pudgy Penguins" ],
	 [ "SEI", "Sei" ],
	 [ "BONK", "Bonk" ],
	 [ "SKY", "Sky" ],
	 [ "TRUMP", "OFFICIAL TRUMP" ],
	 [ "FIL", "Filecoin" ],
	 [ "JUP", "Jupiter" ],
	 [ "IMX", "Immutable" ],
	 [ "FET", "Artificial Superintelligence Alliance" ],
	 [ "GT", "GateToken" ],
	 [ "XDC", "XDC Network" ],
	 [ "OP", "Optimism" ],
	 [ "INJ", "Injective" ],
	 [ "PAXG", "PAX Gold" ],
	 [ "TIA", "Celestia" ],
	 [ "FDUSD", "First Digital USD" ],
	 [ "QNT", "Quant" ],
	 [ "STX", "Stacks" ],
	 [ "LDO", "Lido DAO" ],
	 [ "XAUt", "Tether Gold" ],
	 [ "CAKE", "PancakeSwap" ],
	 [ "KAIA", "Kaia" ],
	 [ "CRV", "Curve DAO Token" ],
	 [ "AERO", "Aerodrome Finance" ],
	 [ "SPX", "SPX6900" ],
	 [ "ZEC", "Zcash" ],
	 [ "GRT", "The Graph" ],
	 [ "PYTH", "Pyth Network" ],
	 [ "NEXO", "Nexo" ],
	 [ "ETHFI", "ether.fi" ],
	 [ "DEXE", "DeXe" ],
	 [ "FLOKI", "FLOKI" ],
	 [ "PENDLE", "Pendle" ],
	 [ "ATH", "Aethir" ],
	 [ "RLUSD", "Ripple USD" ],
	 [ "WIF", "dogwifhat" ],
	 [ "CFX", "Conflux" ],
	 [ "ENS", "Ethereum Name Service" ],
	 [ "0G", "0G" ],
	 [ "XTZ", "Tezos" ],
	 [ "THETA", "Theta Network" ],
	 [ "RAY", "Raydium" ],
	 [ "S", "Sonic" ],
	 [ "SAND", "The Sandbox" ],
	 [ "VIRTUAL", "Virtuals Protocol" ],
	 [ "IOTA", "IOTA" ],
	 [ "GALA", "Gala" ],
	 [ "AB", "AB" ],
	 [ "A", "Vaulta" ],
	 [ "JASMY", "JasmyCoin" ],
	 [ "JTO", "Jito" ],
	 [ "ZRO", "LayerZero" ],
	 [ "EIGEN", "EigenLayer" ],
	 [ "BTT", "BitTorrent [New]" ],
	 [ "MORPHO", "Morpho" ],
	 [ "FARTCOIN", "Fartcoin" ],
	 [ "FLOW", "Flow" ],
	 [ "MANA", "Decentraland" ],
	 [ "WAL", "Walrus" ],
	 [ "TWT", "Trust Wallet Token" ],
	 [ "TUSD", "TrueUSD" ],
	 [ "USDD", "USDD" ],
	 [ "STRK", "Starknet" ],
	 [ "W", "Wormhole" ],
	 [ "BSV", "Bitcoin SV" ],
	 [ "SYRUP", "Maple Finance" ],
	 [ "SUN", "Sun [New]" ],
	 [ "DYDX", "dYdX" ],
	 [ "NFT", "APENFT" ],
	 [ "LINEA", "Linea" ],
	 [ "HNT", "Helium" ],
	 [ "NEO", "Neo" ],
	 [ "AVNT", "Avantis" ],
	 [ "RUNE", "THORChain" ],
	 [ "ZK", "ZKsync" ],
	 [ "BRETT", "Brett (Based)" ],
	 [ "CHZ", "Chiliz" ],
	 [ "APE", "ApeCoin" ],
	 [ "DEEP", "DeepBook Protocol" ],
	 [ "COMP", "Compound" ],
	 [ "CORE", "Core" ],
	 [ "FORM", "Four" ],
	 [ "AR", "Arweave" ],
	 [ "XCN", "Onyxcoin" ],
	 [ "BEAM", "Beam" ],
	 [ "EGLD", "MultiversX" ],
	 [ "ZBCN", "Zebec Network" ],
	 [ "GNO", "Gnosis" ],
	 [ "AXS", "Axie Infinity" ],
	 [ "KAVA", "Kava" ],
	 [ "XEC", "eCash" ],
	 [ "SNX", "Synthetix" ],
	 [ "RSR", "Reserve Rights" ],
	 [ "AIOZ", "AIOZ Network" ],
	 [ "1INCH", "1inch" ],
	 [ "WEMIX", "WEMIX" ],
	 [ "BERA", "Berachain" ],
	 [ "B", "BUILDon" ],
	 [ "SUPER", "SuperVerse" ],
	 [ "JST", "JUST" ],
	 [ "MIRA", "Mira" ],
	 [ "RON", "Ronin" ],
	 [ "AXL", "Axelar" ],
	 [ "FTT", "FTX Token" ],
	 [ "MOVE", "Movement" ],
	 [ "CVX", "Convex Finance" ],
	 [ "LUNC", "Terra Classic" ],
	 [ "PLUME", "Plume" ],
	 [ "TOSHI", "Toshi" ],
	 [ "MERL", "Merlin Chain" ],
	 [ "AKT", "Akash Network" ],
	 [ "MOCA", "Moca Network" ],
	 [ "DCR", "Decred" ],
	 [ "LPT", "Livepeer" ],
	 [ "SNEK", "Snek" ],
	 [ "CTC", "Creditcoin" ],
	 [ "EURC", "EURC" ],
	 [ "AMP", "Amp" ],
	 [ "BARD", "Lombard" ],
	 [ "DASH", "Dash" ],
	 [ "DRIFT", "Drift" ],
	 [ "MOG", "Mog Coin" ],
	 [ "KAITO", "KAITO" ],
	 [ "MX", "MX Token" ],
	 [ "SAFE", "Safe" ],
	 [ "TURBO", "Turbo" ],
	 [ "KSM", "Kusama" ],
	 [ "SFP", "SafePal" ],
	 [ "IOTX", "IoTeX" ],
	 [ "VELO", "Velo" ],
	 [ "MEW", "cat in a dogs world" ],
	 [ "QTUM", "Qtum" ],
	 [ "BIO", "Bio Protocol" ],
	 [ "GLM", "Golem" ],
	 [ "TFUEL", "Theta Fuel" ],
	 [ "BAT", "Basic Attention Token" ],
	 [ "POPCAT", "Popcat (SOL)" ],
	 [ "CHEEMS", "Cheems (cheems.pet)" ],
	 [ "PNUT", "Peanut the Squirrel" ],
	 [ "ZORA", "ZORA" ],
	 [ "ZIL", "Zilliqa" ],
	 [ "JLP", "Jupiter Perps LP" ],
	 [ "FTN", "Fasttoken" ],
	 [ "USDf", "Falcon USD" ],
	 [ "SAROS", "Saros" ],
	 [ "APX", "APX" ],
	 [ "USDG", "Global Dollar" ],
	 [ "USDY", "Ondo US Dollar Yield" ],
	 [ "BDX", "Beldex" ],
	 [ "USD0", "Usual USD" ],
	 [ "VSN", "Vision" ],
	 [ "LION", "Loaded Lions" ],
	 [ "FLUID", "Fluid" ],
	 [ "BORG", "SwissBorg" ],
	 [ "TEL", "Telcoin" ],
	 [ "GHO", "GHO" ],
	 [ "USDF", "Aster USDF" ],
	 [ "DORA", "DORA" ],
	 [ "FRAX", "Legacy Frax Dollar" ],
	 [ "KAU", "Kinesis Gold" ],
	 [ "KTA", "Keeta" ],
	 [ "CCD", "Concordium" ],
	 [ "ULTIMA", "Ultima" ],
	 [ "TIBBIR", "Ribbita by Virtuals" ],
	 [ "LGCT", "Legacy Token" ],
	 [ "STBL", "STBL" ],
	 [ "ALE", "Ailey" ],
	 [ "UPC", "UPCX" ],
	 [ "ZRX", "0x Protocol" ],
	 [ "CKB", "Nervos Network" ],
	 [ "MINA", "Mina" ],
	 [ "SOSO", "SoSoValue" ],
	 [ "BabyDoge", "Baby Doge Coin" ],
	 [ "AIC", "AI Companions" ],
	 [ "GRASS", "Grass" ],
	 [ "SQD", "Subsquid" ],
	 [ "DOG", "Dog (Bitcoin)" ],
	 [ "GAS", "Gas" ],
	 [ "QUBIC", "Qubic" ],
	 [ "SUSHI", "SushiSwap" ],
	 [ "ROSE", "Oasis" ],
	 [ "FRAX", "Frax (prev. FXS)" ],
	 [ "AWE", "AWE" ],
	 [ "GOMINING", "GoМining" ],
	 [ "KMNO", "Kamino Finance" ],
	 [ "VVS", "VVS Finance" ],
	 [ "BLUR", "Blur" ],
	 [ "ASTR", "Astar" ],
	 [ "EUL", "Euler" ],
	 [ "RVN", "Ravencoin" ],
	 [ "PROM", "Prom" ],
	 [ "WHITE", "WhiteRock" ],
	 [ "SAHARA", "Sahara AI" ],
	 [ "OM", "MANTRA" ],
	 [ "YFI", "yearn.finance" ],
	 [ "ORDI", "ORDI" ],
	 [ "ID", "SPACE ID" ],
	 [ "ZETA", "ZetaChain" ],
	 [ "GMX", "GMX" ],
	 [ "ACH", "Alchemy Pay" ],
	 [ "BB", "BounceBit" ],
	 [ "KOGE", "48 Club Token" ],
	 [ "REKT", "Rekt (rektcoin.com)" ],
	 [ "XPR", "XPR Network" ],
	 [ "WMTX", "World Mobile Token" ],
	 [ "NOT", "Notcoin" ],
	 [ "T", "Threshold" ],
	 [ "TRAC", "OriginTrail" ],
	 [ "USELESS", "Useless Coin" ],
	 [ "VTHO", "VeThor Token" ],
	 [ "MPLX", "Metaplex" ],
	 [ "CFG", "Centrifuge" ],
	 [ "TROLL", "TROLL (SOL)" ],
	 [ "HOT", "Holo" ],
	 [ "MELANIA", "Official Melania Meme" ],
	 [ "MOODENG", "Moo Deng (moodengsol.com)" ],
	 [ "CELO", "Celo" ],
	 [ "ETHW", "EthereumPoW" ],
	 [ "SC", "Siacoin" ],
	 [ "EURS", "STASIS EURO" ],
	 [ "COW", "CoW Protocol" ],
	 [ "ELF", "aelf" ],
	 [ "SOMI", "Somnia" ],
	 [ "VENOM", "Venom" ],
	 [ "FLZ", "Fellaz" ],
	 [ "ONE", "Harmony" ],
	 [ "SKL", "SKALE" ],
	 [ "ANKR", "Ankr" ],
	 [ "PROVE", "Succinct" ],
	 [ "RLB", "Rollbit Coin" ],
	 [ "BABY", "Babylon" ],
	 [ "RED", "RedStone" ],
	 [ "STG", "Stargate Finance" ],
	 [ "AUSD", "AUSD" ],
	 [ "DGB", "DigiByte" ],
	 [ "MEME", "Memecoin" ],
	 [ "XCH", "Chia" ],
	 [ "LCX", "LCX" ],
	 [ "YZY", "YZY MONEY" ],
	 [ "XYO", "XYO" ],
	 [ "YU", "Yala" ],
	 [ "PEAQ", "peaq" ],
	 [ "ZIG", "ZIGChain" ],
	 [ "MASK", "Mask Network" ],
	 [ "OMNI", "Omni Network" ],
	 [ "CSPR", "Casper" ],
	 [ "OPEN", "OpenLedger" ],
	 [ "VANA", "Vana" ],
	 [ "ALT", "Altlayer" ],
	 [ "HSK", "HashKey Platform Token" ],
	 [ "ICX", "ICON" ],
	 [ "DEUSD", "Elixir deUSD" ],
	 [ "NPC", "Non-Playable Coin" ],
	 [ "HEMI", "Hemi" ],
	 [ "GEMS", "Gems" ],
	 [ "POLYX", "Polymesh" ],
	 [ "STIK", "Staika" ],
	 [ "NMR", "Numeraire" ],
	 [ "BMX", "BitMart Token" ],
	 [ "LAYER", "Solayer" ],
	 [ "VCNT", "ViciCoin" ],
	 [ "ARKM", "Arkham" ],
	 [ "APEX", "ApeX Protocol" ],
	 [ "GMT", "GMT" ],
	 [ "SATS", "SATS (Ordinals)" ],
	 [ "NXPC", "NEXPACE" ],
	 [ "USDN", "Noble Dollar" ],
	 [ "WOO", "WOO" ],
	 [ "SHFL", "Shuffle" ],
	 [ "NEIRO", "Neiro" ],
	 [ "ORCA", "Orca" ],
	 [ "WAVES", "Waves" ],
	 [ "H", "Humanity Protocol" ],
	 [ "ENJ", "Enjin Coin" ],
	 [ "ALEO", "Aleo" ],
	 [ "BOME", "BOOK OF MEME" ],
	 [ "LRC", "Loopring" ],
	 [ "KDA", "Kadena" ],
	 [ "ZEN", "Horizen" ],
	 [ "SOLO", "Sologenic" ],
	 [ "SLT", "SLT" ],
	 [ "GIGA", "Gigachad" ],
	 [ "ONT", "Ontology" ],
	 [ "ME", "Magic Eden" ],
	 [ "ZKC", "Boundless" ],
	 [ "ORBR", "Orbler" ],
	 [ "KEEP", "Keep Network" ],
	 [ "SNT", "Status" ],
	 [ "IO", "io.net" ],
	 [ "UMA", "UMA" ],
	 [ "RPL", "Rocket Pool" ],
	 [ "BAND", "Band" ],
	 [ "XNO", "Nano" ],
	 [ "KUB", "KUB Coin" ],
	 [ "PCI", "Paycoin" ],
	 [ "SIGN", "Sign" ],
	 [ "COTI", "COTI" ],
	 [ "SXP", "Solar" ],
	 [ "OSMO", "Osmosis" ],
	 [ "REQ", "Request" ],
	 [ "SSV", "ssv.network" ],
	 [ "DUSD", "StandX DUSD" ],
	 [ "CPOOL", "Clearpool" ],
	 [ "G", "Gravity (by Galxe)" ],
	 [ "FUN", "FUNToken" ],
	 [ "WKC", "Wiki Cat" ],
	 [ "XVS", "Venus" ],
	 [ "WILD", "Wilder World" ],
	 [ "FAI", "Freysa" ],
	 [ "LUNA", "Terra" ],
	 [ "GOHOME", "GOHOME" ],
	 [ "BIGTIME", "Big Time" ],
	 [ "SOON", "SOON" ],
	 [ "SXT", "Space and Time" ],
	 [ "STORJ", "Storj" ],
	 [ "AI16Z", "ai16z" ],
	 [ "BLAST", "Blast" ],
	 [ "OSAK", "Osaka Protocol" ],
	 [ "SHX", "Stronghold SHx" ],
	 [ "MBG", "MultiBank Group" ],
	 [ "OMI", "ECOMI" ],
	 [ "HOLO", "Holoworld AI" ],
	 [ "AIXBT", "aixbt" ],
	 [ "BORA", "BORA" ],
	 [ "YGG", "Yield Guild Games" ],
	 [ "QRL", "Quantum Resistant Ledger" ],
	 [ "BICO", "Biconomy" ],
	 [ "HIVE", "Hive" ],
	 [ "REAL", "RealLink" ],
	 [ "RLC", "iExec RLC" ],
	 [ "SPK", "Spark" ],
	 [ "AEVO", "Aevo" ],
	 [ "DSYNC", "Destra Network" ],
	 [ "IOST", "IOST" ],
	 [ "METIS", "Metis" ],
	 [ "HOME", "Defi App" ],
	 [ "CHEX", "Chintai" ],
	 [ "TRB", "Tellor" ],
	 [ "PEOPLE", "ConstitutionDAO" ],
	 [ "ILV", "Illuvium" ],
	 [ "CHEEL", "Cheelee" ]
	 ];

var by_crypto_tag = {};
for(let i of supported_cryptos) by_crypto_tag[i[0]] = i[1];
