#! /bin/sh

if test "$*"
	then
		files="$*"
	else
		files="$(grep -lr ' /usr/bin/python3$' | grep -v pdns.py)"
	fi

f=$(mktemp)
for file in ${files}
do
	echo "===> ${file}"
	python3 -m yapf ${file} > ${f}
	if test -s ${f} && ! cmp ${file} ${f}
		then
			echo "-> ${file}"
			cat ${f} > ${file}
			python3 -m pycodestyle --max-line-length=119 ${file}
		fi
	rm -f ${f}
done
