#! /bin/sh

f=$(mktemp)
for file in $(find -type f -name '*.py')
do
	python3 -m yapf ${file} > ${f}
	if test -s ${f} && ! cmp ${file} ${f}
		then
			echo "-> ${file}"
			cat ${f} > ${file}
			python3 -m pycodestyle --max-line-length=119 ${file}
		fi
	rm -f ${f}
done
