#! /bin/sh

web="$(dd if=/dev/random count=20 bs=1 2>/dev/null | base64 | tr -d '/+=')"
reg="$(dd if=/dev/random count=20 bs=1 2>/dev/null | base64 | tr -d '/+=')"
eng="$(dd if=/dev/random count=20 bs=1 2>/dev/null | base64 | tr -d '/+=')"
dns="$(dd if=/dev/random count=20 bs=1 2>/dev/null | base64 | tr -d '/+=')"

cat default-config/logins.json | \
	sed "s/\[WEBUI-USER-PASSWORD\]/${web}/" | \
	sed "s/\[ENGINE-USER-PASSWORD\]/${eng}/" | \
	sed "s/\[PYRAR-DATABASE-ADMIN-PASSWORD\]/${reg}/" | \
	sed "s/\[PDNS-DATABASE-PASSWORD\]/${dns}/" > /opt/config/logins.json

cat base.sql | \
	sed "s/\[WEBUI-USER-PASSWORD\]/${web}/" | \
	sed "s/\[ENGINE-USER-PASSWORD\]/${eng}/" | \
	sed "s/\[PYRAR-DATABASE-ADMIN-PASSWORD\]/${reg}/" | \
	sed "s/\[PDNS-DATABASE-PASSWORD\]/${dns}/" > /tmp/base.sql

chmod 600 /tmp/base.sql
